variable "app_name" {}
variable "app_env" {}
variable "aws_region" {}
variable "key_name" {}
variable "pb_cidr_block" {}
variable "vpc_cidr_block" {}
#variable "certificate_arn" {}
variable "domain_name" {}
variable "vpc_name" {}
variable "vpc_availability_zones" {}
variable "vpc_public_subnets" {}
variable "vpc_private_subnets" {}
variable "vpc_database_subnets" {}
variable  "vpc_create_database_subnet_group" {}
variable  "vpc_create_database_subnet_route_table"{}   
variable  "vpc_enable_nat_gateway" {}
variable  "vpc_single_nat_gateway" {}
variable MONGODB_URL {}
variable MONGODB_NAME {}
variable MONGODB_USERNAME {}
variable MONGODB_PASSWORD {}
variable image_version {}
variable backend_image {}
variable frontend_image {}